name: Bump Snapshot Package

on:
  workflow_dispatch:
    inputs:
      lts_release:
        type: string
        required: true
      repo:
        type: string
        required: true
      git_hash:
        type: string
        required: true


jobs:
  bump:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: |
          python3 updater.py ${{ github.event.inputs.lts_release }} ${{ github.event.inputs.repo }} ${{ github.event.inputs.git_hash }}
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'New LTS release ${{ github.event.inputs.lts_release }} ${{ github.event.inputs.repo }} ${{ github.event.inputs.git_hash }}'
          new_branch: testing
